[package]
name = "rust_cancellation_token"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-util = "0.7.17"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
select = "0.6.1"
anyhow = "1.0.100"
